In [46]:
import pandas as pd
import xgboost as xgb
import numpy as np
import matplotlib.pyplot as plt

In [47]:
df=pd.read_csv('Iris.csv')

In [48]:
df.drop('Id',axis=1,inplace=True)
df.head()

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0            5.1           3.5            1.4           0.2  Iris-setosa
1            4.9           3.0            1.4           0.2  Iris-setosa
2            4.7           3.2            1.3           0.2  Iris-setosa
3            4.6           3.1            1.5           0.2  Iris-setosa
4            5.0           3.6            1.4           0.2  Iris-setosa

In [49]:
X=df.iloc[:,:-1]
y=df.iloc[:,-1]

In [50]:
y.unique()

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

AttributeError: 'numpy.ndarray' object has no attribute 'unique'

In [51]:
from sklearn.preprocessing import LabelEncoder,OneHotEncoder,LabelBinarizer

In [52]:
le=LabelEncoder()
oh=OneHotEncoder()
la=LabelBinarizer()
encode=le.fit_transform(y)

In [57]:
le.classes_

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

In [55]:
encode

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2], dtype=int64)

In [58]:
one_hot=oh.fit_transform(encode)

C:\Users\Acer\Anaconda3\lib\site-packages\sklearn\utils\validation.py:395: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)


In [60]:
one_hot.toarray()

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1.]])

In [61]:
one_label=la.fit_transform(encode)

In [62]:
one_label

array([[1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0,

In [63]:
X.head()

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0            5.1           3.5            1.4           0.2
1            4.9           3.0            1.4           0.2
2            4.7           3.2            1.3           0.2
3            4.6           3.1            1.5           0.2
4            5.0           3.6            1.4           0.2

In [65]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,one_label)

In [67]:
X_train.shape

(112, 4)

In [68]:
y_train.shape

(112, 3)

In [70]:
from sklearn.tree import DecisionTreeClassifier
dt=DecisionTreeClassifier()

In [72]:
dt.fit(X_train,y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_split=1e-07, min_samples_leaf=1,
            min_samples_split=2, min_weight_fraction_leaf=0.0,
            presort=False, random_state=None, splitter='best')

In [127]:
from keras.models import Sequential
from keras.layers import Dense

model=Sequential()
model.add(Dense(activation='relu',input_dim=4,units=4))
model.add(Dense(10,activation='relu'))
model.add(Dense(3,activation='softmax'))
model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])

In [128]:
model.fit(X_train,y_train,epochs=20,batch_size=10)

Epoch 1/20
112/112 [==============================] - 2s 21ms/step - loss: 1.5658 - acc: 0.3214 
Epoch 2/20
112/112 [=======

In [130]:
y_pred=model.predict(X_test)

In [134]:
y_pred_class=np.argmax(y_pred,axis=1)
y_test_class=np.argmax(y_test,axis=1)

In [133]:
y_pred_class

array([2, 0, 1, 0, 0, 2, 0, 1, 0, 0, 0, 1, 1, 0, 1, 2, 1, 1, 1, 1, 2, 1,
       2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 2, 2, 2, 0, 0, 2], dtype=int64)

In [135]:
y_test_class

array([2, 0, 1, 0, 0, 2, 0, 1, 0, 0, 0, 1, 1, 0, 1, 2, 1, 1, 1, 1, 2, 1,
       2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 2, 1, 2, 0, 0, 2], dtype=int64)

In [136]:
from sklearn.metrics import classification_report

In [139]:
hh=classification_report(y_pred=y_pred_class,y_true=y_test_class)

In [140]:
print(hh)

             precision    recall  f1-score   support

          0       1.00      1.00      1.00        14
          1       1.00      0.92      0.96        12
          2       0.92      1.00      0.96        12

avg / total       0.98      0.97      0.97        38

