In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("googleplaystore_user_reviews.csv")

In [3]:
df.head()

App                                  Translated_Review  \
0  10 Best Foods for You  I like eat delicious food. That's I'm cooking ...   
1  10 Best Foods for You    This help eating healthy exercise regular basis   
2  10 Best Foods for You                                                NaN   
3  10 Best Foods for You         Works great especially going grocery store   
4  10 Best Foods for You                                       Best idea us   

  Sentiment  Sentiment_Polarity  Sentiment_Subjectivity  
0  Positive                1.00                0.533333  
1  Positive                0.25                0.288462  
2       NaN                 NaN                     NaN  
3  Positive                0.40                0.875000  
4  Positive                1.00                0.300000

In [40]:
df.dropna(inplace=True)

In [4]:
import string

In [6]:
df.Translated_Review.str.lower()[0:5]

0    i like eat delicious food. that's i'm cooking ...
1      this help eating healthy exercise regular basis
2                                                  NaN
3           works great especially going grocery store
4                                         best idea us
Name: Translated_Review, dtype: object

In [16]:
kata = "Ball Oh Ball, are you a Ball?"

In [20]:
kata_no_punc = [k for k in kata if k not in string.punctuation]
kata_ubahan = "".join(kata_no_punc)

In [18]:
from sklearn.feature_extraction.text import HashingVectorizer,CountVectorizer,TfidfTransformer,TfidfVectorizer

In [26]:
ct=CountVectorizer()
tf=TfidfVectorizer()
hv = HashingVectorizer()
ct.fit([kata_ubahan])
hv.fit([kata_ubahan])
tf.fit([kata_ubahan])

TfidfVectorizer(analyzer='word', binary=False, decode_error='strict',
        dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=1.0, max_features=None, min_df=1,
        ngram_range=(1, 1), norm='l2', preprocessor=None, smooth_idf=True,
        stop_words=None, strip_accents=None, sublinear_tf=False,
        token_pattern='(?u)\\b\\w\\w+\\b', tokenizer=None, use_idf=True,
        vocabulary=None)

In [33]:
kata_ubahan

'Ball Oh Ball are you a Ball'

In [27]:
ct.vocabulary_

{'are': 0, 'ball': 1, 'oh': 2, 'you': 3}

In [28]:
tf.vocabulary_

{'are': 0, 'ball': 1, 'oh': 2, 'you': 3}

In [30]:
ct.transform([kata_ubahan]).toarray()

array([[1, 3, 1, 1]], dtype=int64)

In [31]:
tf.transform([kata_ubahan]).toarray()

C:\Users\Acer\Anaconda3\lib\site-packages\sklearn\feature_extraction\text.py:1059: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  if hasattr(X, 'dtype') and np.issubdtype(X.dtype, np.float):


array([[0.28867513, 0.8660254 , 0.28867513, 0.28867513]])

In [32]:
hv.transform([kata_ubahan]).toarray()

array([[0., 0., 0., ..., 0., 0., 0.]])

In [38]:
def text_proses(teks):
    teks= str(teks).lower()
    kata_no_punc = [k for k in teks if k not in string.punctuation]
    kata_ubahan = "".join(kata_no_punc)
    return kata_ubahan

In [41]:
df.Translated_Review.apply(text_proses)[0:5]

0    i like eat delicious food thats im cooking foo...
1      this help eating healthy exercise regular basis
3           works great especially going grocery store
4                                         best idea us
5                                             best way
Name: Translated_Review, dtype: object

In [42]:
df.Translated_Review = df.Translated_Review.apply(text_proses)

In [43]:
df.head()

App                                  Translated_Review  \
0  10 Best Foods for You  i like eat delicious food thats im cooking foo...   
1  10 Best Foods for You    this help eating healthy exercise regular basis   
3  10 Best Foods for You         works great especially going grocery store   
4  10 Best Foods for You                                       best idea us   
5  10 Best Foods for You                                           best way   

  Sentiment  Sentiment_Polarity  Sentiment_Subjectivity  
0  Positive                1.00                0.533333  
1  Positive                0.25                0.288462  
3  Positive                0.40                0.875000  
4  Positive                1.00                0.300000  
5  Positive                1.00                0.300000

In [49]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,classification_report
from sklearn.ensemble import RandomForestClassifier

In [50]:
X_train,X_test,y_train,y_test = train_test_split(df.Translated_Review,df.Sentiment,stratify= df.Sentiment)

Dengan CountVectorizer

In [51]:
ct.fit(X_train)

CountVectorizer(analyzer='word', binary=False, decode_error='strict',
        dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=1.0, max_features=None, min_df=1,
        ngram_range=(1, 1), preprocessor=None, stop_words=None,
        strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
        tokenizer=None, vocabulary=None)

In [52]:
X_train_dtm = ct.transform(X_train)
X_test_dtm = ct.transform(X_test)

In [53]:
rf=RandomForestClassifier()

In [54]:
rf.fit(X_train_dtm,y_train)
y_pred=rf.predict(X_test_dtm)
print(classification_report(y_pred=y_pred,y_true=y_test))
print(accuracy_score(y_true=y_test,y_pred=y_pred))

             precision    recall  f1-score   support

   Negative       0.86      0.70      0.77      2068
    Neutral       0.78      0.87      0.82      1289
   Positive       0.90      0.94      0.92      6000

avg / total       0.88      0.88      0.88      9357

0.8775248477075986


Dengan TfIDf

In [55]:
tf.fit(X_train)

TfidfVectorizer(analyzer='word', binary=False, decode_error='strict',
        dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=1.0, max_features=None, min_df=1,
        ngram_range=(1, 1), norm='l2', preprocessor=None, smooth_idf=True,
        stop_words=None, strip_accents=None, sublinear_tf=False,
        token_pattern='(?u)\\b\\w\\w+\\b', tokenizer=None, use_idf=True,
        vocabulary=None)

In [56]:
X_train_dtm = tf.transform(X_train)
X_test_dtm = tf.transform(X_test)

C:\Users\Acer\Anaconda3\lib\site-packages\sklearn\feature_extraction\text.py:1059: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  if hasattr(X, 'dtype') and np.issubdtype(X.dtype, np.float):


In [57]:
rf.fit(X_train_dtm,y_train)
y_pred=rf.predict(X_test_dtm)
print(classification_report(y_pred=y_pred,y_true=y_test))
print(accuracy_score(y_true=y_test,y_pred=y_pred))

             precision    recall  f1-score   support

   Negative       0.87      0.71      0.78      2068
    Neutral       0.81      0.82      0.81      1289
   Positive       0.90      0.95      0.92      6000

avg / total       0.88      0.88      0.88      9357

0.8795554130597414


In [ ]:
"I ate the Fried Chicken" ===> "Ate" ---> "eat"
"The Fried Chicken was eaten by me" ===> "Eaten" ---> "eat"